// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navigation.proto

// Protobuf Java Version: 3.25.1
package com.adamate.aaforaaos.aap.protocol.proto;

public final class NavigationStatus {
  private NavigationStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.adamate.aaforaaos.aap.protocol.proto.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NEXTTURNDETAILS = 32772;</code>
     */
    NEXTTURNDETAILS(32772),
    /**
     * <code>NEXTTURNDISTANCEANDTIME = 32773;</code>
     */
    NEXTTURNDISTANCEANDTIME(32773),
    ;

    /**
     * <code>NEXTTURNDETAILS = 32772;</code>
     */
    public static final int NEXTTURNDETAILS_VALUE = 32772;
    /**
     * <code>NEXTTURNDISTANCEANDTIME = 32773;</code>
     */
    public static final int NEXTTURNDISTANCEANDTIME_VALUE = 32773;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 32772: return NEXTTURNDETAILS;
        case 32773: return NEXTTURNDISTANCEANDTIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.adamate.aaforaaos.aap.protocol.proto.MsgType)
  }

  public interface NextTurnDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string road = 1;</code>
     * @return Whether the road field is set.
     */
    boolean hasRoad();
    /**
     * <code>required string road = 1;</code>
     * @return The road.
     */
    java.lang.String getRoad();
    /**
     * <code>required string road = 1;</code>
     * @return The bytes for road.
     */
    com.google.protobuf.ByteString
        getRoadBytes();

    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
     * @return Whether the side field is set.
     */
    boolean hasSide();
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
     * @return The side.
     */
    com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side getSide();

    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
     * @return Whether the nextturn field is set.
     */
    boolean hasNextturn();
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
     * @return The nextturn.
     */
    com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent getNextturn();

    /**
     * <code>optional bytes turngraph = 4;</code>
     * @return Whether the turngraph field is set.
     */
    boolean hasTurngraph();
    /**
     * <code>optional bytes turngraph = 4;</code>
     * @return The turngraph.
     */
    com.google.protobuf.ByteString getTurngraph();

    /**
     * <code>optional uint32 trunnumer = 5;</code>
     * @return Whether the trunnumer field is set.
     */
    boolean hasTrunnumer();
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     * @return The trunnumer.
     */
    int getTrunnumer();

    /**
     * <code>optional uint32 turnangel = 6;</code>
     * @return Whether the turnangel field is set.
     */
    boolean hasTurnangel();
    /**
     * <code>optional uint32 turnangel = 6;</code>
     * @return The turnangel.
     */
    int getTurnangel();
  }
  /**
   * Protobuf type {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail}
   */
  public static final class NextTurnDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail)
      NextTurnDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NextTurnDetail.newBuilder() to construct.
    private NextTurnDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NextTurnDetail() {
      road_ = "";
      side_ = 1;
      nextturn_ = 0;
      turngraph_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NextTurnDetail();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.class, com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Builder.class);
    }

    /**
     * Protobuf enum {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side}
     */
    public enum Side
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEFT = 1;</code>
       */
      LEFT(1),
      /**
       * <code>RIGHT = 2;</code>
       */
      RIGHT(2),
      /**
       * <code>UNSPECIFIED = 3;</code>
       */
      UNSPECIFIED(3),
      ;

      /**
       * <code>LEFT = 1;</code>
       */
      public static final int LEFT_VALUE = 1;
      /**
       * <code>RIGHT = 2;</code>
       */
      public static final int RIGHT_VALUE = 2;
      /**
       * <code>UNSPECIFIED = 3;</code>
       */
      public static final int UNSPECIFIED_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Side valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Side forNumber(int value) {
        switch (value) {
          case 1: return LEFT;
          case 2: return RIGHT;
          case 3: return UNSPECIFIED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Side>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Side> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Side>() {
              public Side findValueByNumber(int number) {
                return Side.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.getDescriptor().getEnumTypes().get(0);
      }

      private static final Side[] VALUES = values();

      public static Side valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Side(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side)
    }

    /**
     * Protobuf enum {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent}
     */
    public enum NextEvent
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>DEPARTE = 1;</code>
       */
      DEPARTE(1),
      /**
       * <code>NAME_CHANGE = 2;</code>
       */
      NAME_CHANGE(2),
      /**
       * <code>SLIGHT_TURN = 3;</code>
       */
      SLIGHT_TURN(3),
      /**
       * <code>TURN = 4;</code>
       */
      TURN(4),
      /**
       * <code>SHARP_TURN = 5;</code>
       */
      SHARP_TURN(5),
      /**
       * <code>UTURN = 6;</code>
       */
      UTURN(6),
      /**
       * <code>ONRAMPE = 7;</code>
       */
      ONRAMPE(7),
      /**
       * <code>OFFRAMP = 8;</code>
       */
      OFFRAMP(8),
      /**
       * <code>FORME = 9;</code>
       */
      FORME(9),
      /**
       * <code>MERGE = 10;</code>
       */
      MERGE(10),
      /**
       * <code>ROUNDABOUT_ENTER = 11;</code>
       */
      ROUNDABOUT_ENTER(11),
      /**
       * <code>ROUNDABOUT_EXIT = 12;</code>
       */
      ROUNDABOUT_EXIT(12),
      /**
       * <code>ROUNDABOUT_ENTER_AND_EXIT = 13;</code>
       */
      ROUNDABOUT_ENTER_AND_EXIT(13),
      /**
       * <code>STRAIGHTE = 14;</code>
       */
      STRAIGHTE(14),
      /**
       * <code>FERRY_BOAT = 16;</code>
       */
      FERRY_BOAT(16),
      /**
       * <code>FERRY_TRAINE = 17;</code>
       */
      FERRY_TRAINE(17),
      /**
       * <code>DESTINATION = 18;</code>
       */
      DESTINATION(18),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>DEPARTE = 1;</code>
       */
      public static final int DEPARTE_VALUE = 1;
      /**
       * <code>NAME_CHANGE = 2;</code>
       */
      public static final int NAME_CHANGE_VALUE = 2;
      /**
       * <code>SLIGHT_TURN = 3;</code>
       */
      public static final int SLIGHT_TURN_VALUE = 3;
      /**
       * <code>TURN = 4;</code>
       */
      public static final int TURN_VALUE = 4;
      /**
       * <code>SHARP_TURN = 5;</code>
       */
      public static final int SHARP_TURN_VALUE = 5;
      /**
       * <code>UTURN = 6;</code>
       */
      public static final int UTURN_VALUE = 6;
      /**
       * <code>ONRAMPE = 7;</code>
       */
      public static final int ONRAMPE_VALUE = 7;
      /**
       * <code>OFFRAMP = 8;</code>
       */
      public static final int OFFRAMP_VALUE = 8;
      /**
       * <code>FORME = 9;</code>
       */
      public static final int FORME_VALUE = 9;
      /**
       * <code>MERGE = 10;</code>
       */
      public static final int MERGE_VALUE = 10;
      /**
       * <code>ROUNDABOUT_ENTER = 11;</code>
       */
      public static final int ROUNDABOUT_ENTER_VALUE = 11;
      /**
       * <code>ROUNDABOUT_EXIT = 12;</code>
       */
      public static final int ROUNDABOUT_EXIT_VALUE = 12;
      /**
       * <code>ROUNDABOUT_ENTER_AND_EXIT = 13;</code>
       */
      public static final int ROUNDABOUT_ENTER_AND_EXIT_VALUE = 13;
      /**
       * <code>STRAIGHTE = 14;</code>
       */
      public static final int STRAIGHTE_VALUE = 14;
      /**
       * <code>FERRY_BOAT = 16;</code>
       */
      public static final int FERRY_BOAT_VALUE = 16;
      /**
       * <code>FERRY_TRAINE = 17;</code>
       */
      public static final int FERRY_TRAINE_VALUE = 17;
      /**
       * <code>DESTINATION = 18;</code>
       */
      public static final int DESTINATION_VALUE = 18;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NextEvent valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NextEvent forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return DEPARTE;
          case 2: return NAME_CHANGE;
          case 3: return SLIGHT_TURN;
          case 4: return TURN;
          case 5: return SHARP_TURN;
          case 6: return UTURN;
          case 7: return ONRAMPE;
          case 8: return OFFRAMP;
          case 9: return FORME;
          case 10: return MERGE;
          case 11: return ROUNDABOUT_ENTER;
          case 12: return ROUNDABOUT_EXIT;
          case 13: return ROUNDABOUT_ENTER_AND_EXIT;
          case 14: return STRAIGHTE;
          case 16: return FERRY_BOAT;
          case 17: return FERRY_TRAINE;
          case 18: return DESTINATION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NextEvent>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NextEvent> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NextEvent>() {
              public NextEvent findValueByNumber(int number) {
                return NextEvent.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.getDescriptor().getEnumTypes().get(1);
      }

      private static final NextEvent[] VALUES = values();

      public static NextEvent valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NextEvent(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent)
    }

    private int bitField0_;
    public static final int ROAD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object road_ = "";
    /**
     * <code>required string road = 1;</code>
     * @return Whether the road field is set.
     */
    @java.lang.Override
    public boolean hasRoad() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string road = 1;</code>
     * @return The road.
     */
    @java.lang.Override
    public java.lang.String getRoad() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          road_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string road = 1;</code>
     * @return The bytes for road.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoadBytes() {
      java.lang.Object ref = road_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        road_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 2;
    private int side_ = 1;
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
     * @return Whether the side field is set.
     */
    @java.lang.Override public boolean hasSide() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
     * @return The side.
     */
    @java.lang.Override public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side getSide() {
      com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side result = com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side.forNumber(side_);
      return result == null ? com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side.LEFT : result;
    }

    public static final int NEXTTURN_FIELD_NUMBER = 3;
    private int nextturn_ = 0;
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
     * @return Whether the nextturn field is set.
     */
    @java.lang.Override public boolean hasNextturn() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
     * @return The nextturn.
     */
    @java.lang.Override public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent getNextturn() {
      com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent result = com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent.forNumber(nextturn_);
      return result == null ? com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent.UNKNOWN : result;
    }

    public static final int TURNGRAPH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString turngraph_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes turngraph = 4;</code>
     * @return Whether the turngraph field is set.
     */
    @java.lang.Override
    public boolean hasTurngraph() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes turngraph = 4;</code>
     * @return The turngraph.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTurngraph() {
      return turngraph_;
    }

    public static final int TRUNNUMER_FIELD_NUMBER = 5;
    private int trunnumer_ = 0;
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     * @return Whether the trunnumer field is set.
     */
    @java.lang.Override
    public boolean hasTrunnumer() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 trunnumer = 5;</code>
     * @return The trunnumer.
     */
    @java.lang.Override
    public int getTrunnumer() {
      return trunnumer_;
    }

    public static final int TURNANGEL_FIELD_NUMBER = 6;
    private int turnangel_ = 0;
    /**
     * <code>optional uint32 turnangel = 6;</code>
     * @return Whether the turnangel field is set.
     */
    @java.lang.Override
    public boolean hasTurnangel() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 turnangel = 6;</code>
     * @return The turnangel.
     */
    @java.lang.Override
    public int getTurnangel() {
      return turnangel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoad()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSide()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNextturn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, road_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, side_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, nextturn_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, turngraph_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, trunnumer_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, turnangel_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, road_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, side_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, nextturn_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, turngraph_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, trunnumer_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, turnangel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail)) {
        return super.equals(obj);
      }
      com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail other = (com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail) obj;

      if (hasRoad() != other.hasRoad()) return false;
      if (hasRoad()) {
        if (!getRoad()
            .equals(other.getRoad())) return false;
      }
      if (hasSide() != other.hasSide()) return false;
      if (hasSide()) {
        if (side_ != other.side_) return false;
      }
      if (hasNextturn() != other.hasNextturn()) return false;
      if (hasNextturn()) {
        if (nextturn_ != other.nextturn_) return false;
      }
      if (hasTurngraph() != other.hasTurngraph()) return false;
      if (hasTurngraph()) {
        if (!getTurngraph()
            .equals(other.getTurngraph())) return false;
      }
      if (hasTrunnumer() != other.hasTrunnumer()) return false;
      if (hasTrunnumer()) {
        if (getTrunnumer()
            != other.getTrunnumer()) return false;
      }
      if (hasTurnangel() != other.hasTurnangel()) return false;
      if (hasTurnangel()) {
        if (getTurnangel()
            != other.getTurnangel()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoad()) {
        hash = (37 * hash) + ROAD_FIELD_NUMBER;
        hash = (53 * hash) + getRoad().hashCode();
      }
      if (hasSide()) {
        hash = (37 * hash) + SIDE_FIELD_NUMBER;
        hash = (53 * hash) + side_;
      }
      if (hasNextturn()) {
        hash = (37 * hash) + NEXTTURN_FIELD_NUMBER;
        hash = (53 * hash) + nextturn_;
      }
      if (hasTurngraph()) {
        hash = (37 * hash) + TURNGRAPH_FIELD_NUMBER;
        hash = (53 * hash) + getTurngraph().hashCode();
      }
      if (hasTrunnumer()) {
        hash = (37 * hash) + TRUNNUMER_FIELD_NUMBER;
        hash = (53 * hash) + getTrunnumer();
      }
      if (hasTurnangel()) {
        hash = (37 * hash) + TURNANGEL_FIELD_NUMBER;
        hash = (53 * hash) + getTurnangel();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail)
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.class, com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Builder.class);
      }

      // Construct using com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        road_ = "";
        side_ = 1;
        nextturn_ = 0;
        turngraph_ = com.google.protobuf.ByteString.EMPTY;
        trunnumer_ = 0;
        turnangel_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor;
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail getDefaultInstanceForType() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.getDefaultInstance();
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail build() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail buildPartial() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail result = new com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.road_ = road_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.side_ = side_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.nextturn_ = nextturn_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.turngraph_ = turngraph_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.trunnumer_ = trunnumer_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.turnangel_ = turnangel_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail) {
          return mergeFrom((com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail other) {
        if (other == com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.getDefaultInstance()) return this;
        if (other.hasRoad()) {
          road_ = other.road_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSide()) {
          setSide(other.getSide());
        }
        if (other.hasNextturn()) {
          setNextturn(other.getNextturn());
        }
        if (other.hasTurngraph()) {
          setTurngraph(other.getTurngraph());
        }
        if (other.hasTrunnumer()) {
          setTrunnumer(other.getTrunnumer());
        }
        if (other.hasTurnangel()) {
          setTurnangel(other.getTurnangel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRoad()) {
          return false;
        }
        if (!hasSide()) {
          return false;
        }
        if (!hasNextturn()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                road_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                int tmpRaw = input.readEnum();
                com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side tmpValue =
                    com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(2, tmpRaw);
                } else {
                  side_ = tmpRaw;
                  bitField0_ |= 0x00000002;
                }
                break;
              } // case 16
              case 24: {
                int tmpRaw = input.readEnum();
                com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent tmpValue =
                    com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(3, tmpRaw);
                } else {
                  nextturn_ = tmpRaw;
                  bitField0_ |= 0x00000004;
                }
                break;
              } // case 24
              case 34: {
                turngraph_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                trunnumer_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                turnangel_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object road_ = "";
      /**
       * <code>required string road = 1;</code>
       * @return Whether the road field is set.
       */
      public boolean hasRoad() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string road = 1;</code>
       * @return The road.
       */
      public java.lang.String getRoad() {
        java.lang.Object ref = road_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            road_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string road = 1;</code>
       * @return The bytes for road.
       */
      public com.google.protobuf.ByteString
          getRoadBytes() {
        java.lang.Object ref = road_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          road_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string road = 1;</code>
       * @param value The road to set.
       * @return This builder for chaining.
       */
      public Builder setRoad(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        road_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string road = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoad() {
        road_ = getDefaultInstance().getRoad();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string road = 1;</code>
       * @param value The bytes for road to set.
       * @return This builder for chaining.
       */
      public Builder setRoadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        road_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int side_ = 1;
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
       * @return Whether the side field is set.
       */
      @java.lang.Override public boolean hasSide() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
       * @return The side.
       */
      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side getSide() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side result = com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side.forNumber(side_);
        return result == null ? com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side.LEFT : result;
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
       * @param value The side to set.
       * @return This builder for chaining.
       */
      public Builder setSide(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.Side value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        side_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.Side side = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSide() {
        bitField0_ = (bitField0_ & ~0x00000002);
        side_ = 1;
        onChanged();
        return this;
      }

      private int nextturn_ = 0;
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
       * @return Whether the nextturn field is set.
       */
      @java.lang.Override public boolean hasNextturn() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
       * @return The nextturn.
       */
      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent getNextturn() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent result = com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent.forNumber(nextturn_);
        return result == null ? com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent.UNKNOWN : result;
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
       * @param value The nextturn to set.
       * @return This builder for chaining.
       */
      public Builder setNextturn(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail.NextEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        nextturn_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail.NextEvent nextturn = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNextturn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nextturn_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString turngraph_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes turngraph = 4;</code>
       * @return Whether the turngraph field is set.
       */
      @java.lang.Override
      public boolean hasTurngraph() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       * @return The turngraph.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTurngraph() {
        return turngraph_;
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       * @param value The turngraph to set.
       * @return This builder for chaining.
       */
      public Builder setTurngraph(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        turngraph_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes turngraph = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTurngraph() {
        bitField0_ = (bitField0_ & ~0x00000008);
        turngraph_ = getDefaultInstance().getTurngraph();
        onChanged();
        return this;
      }

      private int trunnumer_ ;
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       * @return Whether the trunnumer field is set.
       */
      @java.lang.Override
      public boolean hasTrunnumer() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       * @return The trunnumer.
       */
      @java.lang.Override
      public int getTrunnumer() {
        return trunnumer_;
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       * @param value The trunnumer to set.
       * @return This builder for chaining.
       */
      public Builder setTrunnumer(int value) {

        trunnumer_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 trunnumer = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrunnumer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trunnumer_ = 0;
        onChanged();
        return this;
      }

      private int turnangel_ ;
      /**
       * <code>optional uint32 turnangel = 6;</code>
       * @return Whether the turnangel field is set.
       */
      @java.lang.Override
      public boolean hasTurnangel() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       * @return The turnangel.
       */
      @java.lang.Override
      public int getTurnangel() {
        return turnangel_;
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       * @param value The turnangel to set.
       * @return This builder for chaining.
       */
      public Builder setTurnangel(int value) {

        turnangel_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 turnangel = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTurnangel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        turnangel_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail)
    }

    // @@protoc_insertion_point(class_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDetail)
    private static final com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail();
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NextTurnDetail>
        PARSER = new com.google.protobuf.AbstractParser<NextTurnDetail>() {
      @java.lang.Override
      public NextTurnDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NextTurnDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NextTurnDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NextTurnDistanceEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 distance = 1;</code>
     * @return Whether the distance field is set.
     */
    boolean hasDistance();
    /**
     * <code>optional uint32 distance = 1;</code>
     * @return The distance.
     */
    int getDistance();

    /**
     * <code>optional uint32 time = 2;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>optional uint32 time = 2;</code>
     * @return The time.
     */
    int getTime();
  }
  /**
   * Protobuf type {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent}
   */
  public static final class NextTurnDistanceEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent)
      NextTurnDistanceEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NextTurnDistanceEvent.newBuilder() to construct.
    private NextTurnDistanceEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NextTurnDistanceEvent() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NextTurnDistanceEvent();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.class, com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.Builder.class);
    }

    private int bitField0_;
    public static final int DISTANCE_FIELD_NUMBER = 1;
    private int distance_ = 0;
    /**
     * <code>optional uint32 distance = 1;</code>
     * @return Whether the distance field is set.
     */
    @java.lang.Override
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 distance = 1;</code>
     * @return The distance.
     */
    @java.lang.Override
    public int getDistance() {
      return distance_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private int time_ = 0;
    /**
     * <code>optional uint32 time = 2;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, time_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent)) {
        return super.equals(obj);
      }
      com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent other = (com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent) obj;

      if (hasDistance() != other.hasDistance()) return false;
      if (hasDistance()) {
        if (getDistance()
            != other.getDistance()) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (getTime()
            != other.getTime()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDistance()) {
        hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getDistance();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent)
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.class, com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.Builder.class);
      }

      // Construct using com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        distance_ = 0;
        time_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor;
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent getDefaultInstanceForType() {
        return com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent build() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent buildPartial() {
        com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent result = new com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.distance_ = distance_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.time_ = time_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent) {
          return mergeFrom((com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent other) {
        if (other == com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent.getDefaultInstance()) return this;
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                distance_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                time_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int distance_ ;
      /**
       * <code>optional uint32 distance = 1;</code>
       * @return Whether the distance field is set.
       */
      @java.lang.Override
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       * @return The distance.
       */
      @java.lang.Override
      public int getDistance() {
        return distance_;
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(int value) {

        distance_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 distance = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = 0;
        onChanged();
        return this;
      }

      private int time_ ;
      /**
       * <code>optional uint32 time = 2;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional uint32 time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {

        time_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent)
    }

    // @@protoc_insertion_point(class_scope:com.adamate.aaforaaos.aap.protocol.proto.NextTurnDistanceEvent)
    private static final com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent();
    }

    public static com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NextTurnDistanceEvent>
        PARSER = new com.google.protobuf.AbstractParser<NextTurnDistanceEvent>() {
      @java.lang.Override
      public NextTurnDistanceEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NextTurnDistanceEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NextTurnDistanceEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.adamate.aaforaaos.aap.protocol.proto.NavigationStatus.NextTurnDistanceEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020navigation.proto\0221com.adamate.headu" +
      "nitrevived.aap.protocol.proto\"\345\004\n\016NextTu" +
      "rnDetail\022\014\n\004road\030\001 \002(\t\022T\n\004side\030\002 \002(\0162F.c" +
      "om..aap.protoc" +
      "ol.proto.NextTurnDetail.Side\022]\n\010nextturn" +
      "\030\003 \002(\0162K.com.adamate.aaforaaos." +
      "aap.protocol.proto.NextTurnDetail.NextEv" +
      "ent\022\021\n\tturngraph\030\004 \001(\014\022\021\n\ttrunnumer\030\005 \001(" +
      "\r\022\021\n\tturnangel\030\006 \001(\r\",\n\004Side\022\010\n\004LEFT\020\001\022\t" +
      "\n\005RIGHT\020\002\022\017\n\013UNSPECIFIED\020\003\"\250\002\n\tNextEvent" +
      "\022\013\n\007UNKNOWN\020\000\022\013\n\007DEPARTE\020\001\022\017\n\013NAME_CHANG" +
      "E\020\002\022\017\n\013SLIGHT_TURN\020\003\022\010\n\004TURN\020\004\022\016\n\nSHARP_" +
      "TURN\020\005\022\t\n\005UTURN\020\006\022\013\n\007ONRAMPE\020\007\022\013\n\007OFFRAM" +
      "P\020\010\022\t\n\005FORME\020\t\022\t\n\005MERGE\020\n\022\024\n\020ROUNDABOUT_" +
      "ENTER\020\013\022\023\n\017ROUNDABOUT_EXIT\020\014\022\035\n\031ROUNDABO" +
      "UT_ENTER_AND_EXIT\020\r\022\r\n\tSTRAIGHTE\020\016\022\016\n\nFE" +
      "RRY_BOAT\020\020\022\020\n\014FERRY_TRAINE\020\021\022\017\n\013DESTINAT" +
      "ION\020\022\"7\n\025NextTurnDistanceEvent\022\020\n\010distan" +
      "ce\030\001 \001(\r\022\014\n\004time\030\002 \001(\r*?\n\007MsgType\022\025\n\017NEX" +
      "TTURNDETAILS\020\204\200\002\022\035\n\027NEXTTURNDISTANCEANDT" +
      "IME\020\205\200\002B\022B\020NavigationStatus"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDetail_descriptor,
        new java.lang.String[] { "Road", "Side", "Nextturn", "Turngraph", "Trunnumer", "Turnangel", });
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_adamate_aaforaaos_aap_protocol_proto_NextTurnDistanceEvent_descriptor,
        new java.lang.String[] { "Distance", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
